version: 'v1'

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    networks:
      - lan_services
    links:
      - mongo2
      - mongo3
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0"
      ]
  mongo2:
    container_name: mongo2
    image: mongo:4.4
    networks:
      - lan_services
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0"
      ]
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    networks:
      - lan_services
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0"
      ]
  script:
    container_name: nodejs
    build: ./app_mongodb
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - lan_services
networks:
  lan_services:
    driver: bridge
